# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Steven Wang`s World - 记录 | 思考 "
description: ""
email: mail@steven.wang
logo: "/assets/images/ed_logo.png"
cover: "/assets/images/desktop.png"
name: 'Steven Wang'
author: 'Steven Wang'
author_image: "/assets/images/author.png"
paginate:	15
url: "https://steven.wang" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/cnstevenwang
    desc:	Fork me on github

comments :
provider : duoshuo
duoshuo :
    short_name : StevenWang

# default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
theme: jekyll-theme-tactile