title: Steven Wang`s World
description: Someone who wants to be a simple and peaceful boy.
slogan: A simple and peaceful boy.

url: "http://steven.wang"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: cnstevenwang

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"