# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Steven Wang`s World - 记录思考 "
description: ""
email: 281583051@qq.com
logo: "/assets/images/ed_logo.png"
cover: "/assets/images/desktop.png "
wechat: "微信:oulaoula"
name: 'Steven Wang'
author: 'Steven Wang'
author_image: "/assets/images/author.png"
paginate:	15
url: "http://cnedwan.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	weibo
    url:	http://weibo.com/netols
    desc: Connect with me weibo

  - icon:	github
    url:	https://github.com/cnstevenwang
    desc:	Fork me on github

comments :
provider : duoshuo
duoshuo :
    short_name : edwan
